/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankclient;

import Server.Account;
import Server.Customer;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class CustomerForm extends javax.swing.JFrame {

    private Customer customer = null;
    private Account[] acountArray = new Account[10];
    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();
    }
    public CustomerForm(Customer customer) {
        
        this.customer = customer;
        
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);
        
        Refresh();
    }
    private void Refresh()
    {
        int id = customer.getId();
        acountArray = BankClient.GetCustomerAccounts(id);
        //String [] tab = new String[lista.length];
        checkBoxAcc.removeAllItems();
        //listAcc.removeAll();
        final DefaultListModel vegName = new DefaultListModel();     
      
        for(int i= 0; i< acountArray.length; i++)
        {
            vegName.addElement(acountArray[i].getAccountNumber());
            //tab[i] = lista[i].getAccountNumber();
            checkBoxAcc.addItem(acountArray[i].getAccountNumber());
            //checkBoxAcc.addItem( new ComboItem(lista[i].getId(), lista[i].getAccountNumber()) );
            //checkBoxAcc.addItem( lista[i.t );
        }
        //listAcc = new JList(vegName);  
        //listAcc.setVisibleRowCount(13); 
        //listAcc.setLayoutOrientation(JList.VERTICAL);
        //listAcc.repaint();
        //listAcc.revalidate();
    }
    public JLabel getLabelCustomer()
    {
        return labelCustomer;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        labelCustomer = new javax.swing.JLabel();
        btnRefreshAccount = new javax.swing.JButton();
        checkBoxAcc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnBalance = new javax.swing.JButton();
        btnNewAccount = new javax.swing.JButton();
        btnLodgement = new javax.swing.JButton();
        btnWithdrawal = new javax.swing.JButton();
        btnTransactions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank online");
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Bank online application");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        labelCustomer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCustomer.setText("jLabel2");

        btnRefreshAccount.setText("Refresh account list");
        btnRefreshAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshAccountActionPerformed(evt);
            }
        });

        checkBoxAcc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Choose account ");

        btnBalance.setText("Check balance");
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });

        btnNewAccount.setText("New Accoun");
        btnNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccountActionPerformed(evt);
            }
        });

        btnLodgement.setText("Lodgement");
        btnLodgement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLodgementActionPerformed(evt);
            }
        });

        btnWithdrawal.setText("Withdrawal");
        btnWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawalActionPerformed(evt);
            }
        });

        btnTransactions.setText("View transactions");
        btnTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(checkBoxAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRefreshAccount)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnLogout)
                                        .addComponent(btnNewAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLodgement, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnWithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(btnTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(labelCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshAccount))
                .addGap(18, 18, 18)
                .addComponent(btnNewAccount)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBalance)
                    .addComponent(btnLodgement)
                    .addComponent(btnWithdrawal)
                    .addComponent(btnTransactions))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        JOptionPane.showMessageDialog(new JFrame(),
            "Logout correct, thank you for your visit!");
        BankClientForm fr = new BankClientForm();
        fr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRefreshAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshAccountActionPerformed
        Refresh();
    }//GEN-LAST:event_btnRefreshAccountActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
        int id = -1;
        // get id for account:
        String item = (String)checkBoxAcc.getSelectedItem();
        for(int i = 0; i < acountArray.length; i++)
        {
            if(item.equals(acountArray[i].getAccountNumber()))
            {
                id = acountArray[i].getId();
            }
        }
        
        String balance = BankClient.GetAccountBalance(id);
        
        if(balance == "null") balance = "0.00";
        JOptionPane.showMessageDialog(new JFrame(),
            "Balance is €" + balance);
    }//GEN-LAST:event_btnBalanceActionPerformed

    private void btnNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccountActionPerformed
        
        NewAccountFrame fr = new NewAccountFrame(customer);
        fr.setVisible(true);
        Refresh();
    }//GEN-LAST:event_btnNewAccountActionPerformed

    private Account currentAccount()
    {
        Account currentAccount = null;
        String item = (String)checkBoxAcc.getSelectedItem();
        for(int i = 0; i < acountArray.length; i++)
        {
            if(item.equals(acountArray[i].getAccountNumber()))
            {
                currentAccount= acountArray[i];
            }
        }
        return currentAccount;
    }
    private void btnTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionsActionPerformed
               
        ViewTransactionForm fm = new ViewTransactionForm(currentAccount());
        fm.setVisible(true);
    }//GEN-LAST:event_btnTransactionsActionPerformed

    private void btnLodgementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLodgementActionPerformed
        TransactionForm fm = new TransactionForm(currentAccount(), "plus");
        fm.GetLabelTyp().setText("Lodgement");
        fm.setVisible(true);
    }//GEN-LAST:event_btnLodgementActionPerformed

    private void btnWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawalActionPerformed
        TransactionForm fm = new TransactionForm(currentAccount(), "minus");
         fm.GetLabelTyp().setText("Withdrawal");
        fm.setVisible(true);
    }//GEN-LAST:event_btnWithdrawalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnLodgement;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewAccount;
    private javax.swing.JButton btnRefreshAccount;
    private javax.swing.JButton btnTransactions;
    private javax.swing.JButton btnWithdrawal;
    private javax.swing.JComboBox<String> checkBoxAcc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCustomer;
    // End of variables declaration//GEN-END:variables

private class ComboItem {

    private int value;
    private String label;

    public ComboItem(int value, String label) {
        this.value = value;
        this.label = label;
    }

    public int getValue() {
        return this.value;
    }

    public String getLabel() {
        return this.label;
    }

    @Override
    public String toString() {
        return label;
    }
}
}
